eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.refresh.enable=false
server.port=8761


spring.cloud.config.server.security.enabled=false

#Actuator prometeus endpoint
management.endpoints.web.exposure.include=prometheus